### ISSUE TITLE
Vulkan backend black screen

### ISSUE THREAD

**Issue by rmalca** [mellinoe/veldrid-samples#10]
In the sample "GettingStarted" when I change
`_graphicsDevice = VeldridStartup.CreateGraphicsDevice(window);`
for this
`_graphicsDevice = VeldridStartup.CreateGraphicsDevice(window, GraphicsBackend.Vulkan);`
I get a black screen without any warnings.

Any idea what it could be? Vulkan SDK Cube works fine.

**Comment by mellinoe** [comment]
The vertex data provided in that sample is "upside down" in Vulkan by default, unless an optional setting is enabled. This should work:

```C#
GraphicsDeviceOptions options = new GraphicsDeviceOptions() { PreferStandardClipSpaceYDirection = true };
_graphicsDevice = VeldridStartup.CreateGraphicsDevice(window, options, GraphicsBackend.Vulkan);
```

**Comment by lweb20** [comment]
> The vertex data provided in that sample is "upside down" in Vulkan by default, unless an optional setting is enabled. This should work:
> 
> ```cs
> GraphicsDeviceOptions options = new GraphicsDeviceOptions() { PreferStandardClipSpaceYDirection = true };
> _graphicsDevice = VeldridStartup.CreateGraphicsDevice(window, options, GraphicsBackend.Vulkan);
> ```

Perfect, it works now. Thanks!
